image: node:18

stages:
  - install
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

build_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test_app:
  stage: test
  script:
    - npm run test -- --coverage
  artifacts:
    paths:
      - coverage/


deploy_to_vercel:
  stage: deploy
  image: node:18
  only:
    - main  
  script:
    - npm install -g vercel
    - vercel --token=$VERCEL_TOKEN --prod --yes