image: node:18

stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

build_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
